[General]
sensor_location_name = sensor-location
sensor_type = auto
minutes_between_reads = 5
sensor_threshold_temp = 88.0
sensor_lower_threshold_temp = 40.0
threshold_count = 3
slack_channel = alerts
slack_api_token = xoxb-slack-api-key
dashboard_url = https://yourdomain.com/dashboard/api/submit.php
dashboard_api_key = change-me-to-a-secure-random-key
bme280_address = 0x76
